### ISSUE TITLE
Verification Suites

### ISSUE THREAD

**Issue by mattcollier** [veres-one/did-veres-one#12]
Here is a proposal related to simplifying proof types: https://github.com/digitalbazaar/jsonld-signatures/pull/37#issuecomment-439081113

Here is a sample DID document: https://gist.github.com/mattcollier/123bcd73881e9160cb522bca857be673#file-maintainerdiddoc-json-L21

The proposal is that the `type` found on L7,21,35 would all be the same value.  And that value (for now) would be one of two: `Ed25519SignatureVerification2018`, `RsaSignatureVerification2018`

This type would indicate what sort of verification material should be expected in the suite document.  Both of these types would include a `publicKey` property (as now) that includes keys of the proper corresponding types: `Ed25519VerificationKey2018`, `RsaVerificationKey2018`

We foresee that other types of verification may be desirable that provide different meta data.  Such as fingerprint verification.

Have I summarized this properly?

If so, could we simplify further for the types found on L7,21,35 and use one unifying term `CryptographicSignatureVerification2018`?  This would allow the suite document to contain public keys of multiple types.  What we are trying to communicate with this `type` is that one should be looking for a `publicKey` property in the suite document which any asymmetric algorithm would have.

I am looking to get final agreement on this proposal so that we can start coding it up.

**Comment by dmitrizagidulin** [comment]
I'm not sure generalizing to just a `CryptographicSignatureVerification2018` would work? (Because I think there may be instances of cryptographic signature verifications where a single `publicKey` property is not sufficient, like some of the ZKP stuff)

**Comment by mattcollier** [comment]
So, if the suite document has different meta data for ZKP, it would needs its own type of `ZkpSignatureVerification2018`?

**Comment by msporny** [comment]
> Have I summarized this properly?

More or less, I think so.

If > so, could we simplify further for the types found on L7,21,35 and use one unifying term CryptographicSignatureVerification2018?

No, we can't... because some organizations/government will not allow Secp256k1 and others may allow it (pick your favorite asymmetric cryptography suite). So, we need a way to differentiate an RSA-based suite from an Ed25519-based suite. 

The fundamental question is: How do I suggest to the software that I'm only okay with RSA-based signatures and nothing else?

**Comment by msporny** [comment]
> So, if the suite document has different meta data for ZKP, it would needs its own type of ZkpSignatureVerification2018?

Yes.

**Comment by mattcollier** [comment]
@msporny the key itself is the differentiator.  In the case of having a requirement for the RSA cryptographic algorithm, one would look for the `CryptographicSignatureVerification2018` suite, then look for a `RsaVerificationKey2018`.

**Comment by msporny** [comment]
> @msporny the key itself is the differentiator. In the case of having a requirement for the RSA cryptographic algorithm, one would look for the CryptographicSignatureVerification2018 suite, then look for a RsaVerificationKey2018.

How do I tell the software what key I find acceptable? What method call do I make? Where do I pass the option?

**Comment by mattcollier** [comment]
The latest jsonld-signatures.verify API is like this:
* the proofVerification bit is *not* done which is why we're having this conversation.  We need to figure out this API whatever the case
```
jsigs.verify(document, {
  purpose: {
    proofPurpose: 'positivelyPleasingProofPurpose',
    // the ocapld.js handle proofPurpose handler would be built to work with rsa/ed26619 suites
    // `proofVerification` only need be provided if one would like to modify default behavior (e.g. restrict 
    // type of crypto
    proofVerification: [{ 
       suite: 'CryptographicSignatureVerification2018',
       key: {
          id: 'did:v1:test:nym:z279vjx5yNR7AbSS3sYfztXnaKrjtziURFtJ59pWeNhWb6Kq#positively-pleasing-key-1'
          type: ['RsaVerificationKey2018'] // Ed25519VerificationKey2018 is not included
   }, {
       suite: `FingerprintVerification2018`, // suite tells us what metadata is to be expected
       provider: [`ios`, `android`]
  }]
}
```
So, here we just query the `publicKey` array found in the `CryptographicSignatureVerification2018` suite for keys that match the specified `key`.

I guess it doesn't make sense to me that we're calling these "verification suites" which by definition is a "group of things", and then we're saying that this suite really only does *one* thing.  So the 1:1 relationship between suite type and key type seems to just lead to more types needing to be invented and maintained.

**Comment by dlongley** [comment]
Maybe an `RsaVerificationKey2018` *is* a "verification suite"? :) ... just going to float that out there as a possible way to eliminate the need for another layer here.

**Comment by mattcollier** [comment]
@dlongley can you say more about that idea?  Maybe you could fork the sample DID document if it impacts the structure of that document.

**Comment by dlongley** [comment]
@mattcollier,

Sure, we just remove one level of nesting, essentially:

https://gist.github.com/dlongley/d2f12d6c8aafe72ce25fcdf5258081f2

**Comment by mattcollier** [comment]
@dlongley I love it!  What was the inspiration for the capability suite as it exists today?

**Comment by dlongley** [comment]
@mattcollier,

> What was the inspiration for the capability suite as it exists today?

I think we were just filling in a "verification suite" because we knew that was the architecture ... and giving it a single parameter `publicKey`. The architecture needed to allow for suites with other parameters.

But it seems like we could consider verification keys to be "verification suites" that have the parameters `controller` and something else representing the key material (e.g. `publicKeyBase58`, `publicKeyPem`, `publicKeyCoseBase58OrSomething`). I'm not sure what we lose by doing this; if the answer is nothing it seems like the best way to go.

**Comment by mattcollier** [comment]
Closing this.  Verification Suites have been removed.
