### ISSUE TITLE
Public key IDs must include #<pub key cryptonym>

### ISSUE THREAD

**Issue by dmitrizagidulin** [veres-one/did-veres-one#13]
Change public key IDs to use `did:v1:nym:1234#<public key cryptonym>` and verify these (require them) when keys are added to a DID Document. This is related to GDPRing all the things.

**Comment by dlongley** [comment]
@dmitrizagidulin, I'm going to take this one off your plate, that ok? This will need code fixes in both veres one validator code and in did-io/veres-one code.

**Comment by dlongley** [comment]
Closed via #14 and #15.
