### ISSUE TITLE
Add mock support for Ticket Service

### ISSUE THREAD

**Issue by dmitrizagidulin** [veres-one/did-veres-one#16]
Notes from chat.

Something like:  

```js
{
  type: 'GraphCycleProof2018', 
  powDifficulty: <base64Url-encoded blob>, 
  proofValue: <base64Url-encoded blob>
}
```

dlongley: powDifficulty is just an integer and proofValue is an array of integers and some other stuff   
so... the client is going to contact a ticket service, get a ticket, do a PoW on it + their operation, send it to the ticket service and get their operation back with an ocap invocation proof on it .

after you get the operation back with the invocation proof on it, you follow the same code path as the accelerator version

**Comment by dlongley** [comment]
We might not need to have `powDifficulty` on there, so let's leave that off for now:

```js
{
  type: 'GraphCycleProof2018', 
  proofValue: <base64Url-encoded blob>
}
```

**Comment by dlongley** [comment]
Closing this as the ticketing service will no longer be used, replace with "earned storage" instead.
