### ISSUE TITLE
Remove apisauce

### ISSUE THREAD

**Issue by dlongley** [veres-one/did-veres-one#64]
Use `@digitalbazaar/http-client` wherever necessary as a replacement for `apisauce` and `axios`.

**Comment by aljones15** [comment]
note: this should be closed with the release of `14`: https://github.com/veres-one/did-veres-one/pull/60/files

**Comment by mattcollier** [comment]
I still see `apisauce` listed in deps for the `14.x` branch:

https://github.com/veres-one/did-veres-one/blob/v14.x/package.json

Is this an unused dependency?

**Comment by dmitrizagidulin** [comment]
Yep, unused, safe to remove

**Comment by davidlehn** [comment]
Should be addressed in 15.0.0 (on main now).
