### ISSUE TITLE
Add v1.generate({seed}) feature, to match did:key driver

### ISSUE THREAD

**Issue by dmitrizagidulin** [veres-one/did-veres-one#74]
Add the ability to generate a new Veres One DID from a seed, to match did:key driver.
(Just like with did:key, if a `seed` param is present, use it to generate a `capabilityInvocation` key.)

Note: Make the PR off of https://github.com/veres-one/did-veres-one/pull/60 / `v14.x` branch.

**Comment by msporny** [comment]
Where do we use this feature? Why do we need it?

**Comment by dmitrizagidulin** [comment]
@msporny - we use this in `did-io`, and were using it in our admin CLI tool.

**Comment by msporny** [comment]
> @msporny - we use this in `did-io`, and were using it in our admin CLI tool.

Yes, but why? What's the use case?

**Comment by aljones15** [comment]
just a small note, this makes `did-veres-one` have the same `generate` interface as `did-method-key`. This helps as right now if you want your app to be cross-compatible with `did-method-key` and `did-veres-one` you have to generate `did-method-key` from a 32-byte `Uint8Array` and then `did-veres-one` from an Ed25519Key. Basically, `did-veres-one` requires an extra step.

**Comment by aljones15** [comment]
I believe this can be closed as this was is now a feature in `v14.x` https://github.com/veres-one/did-veres-one/pull/75

**Comment by JSAssassin** [comment]
Closing, implemented.
